// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCT33HQ8W7qjNy7GEaLlMHH46p40_ohqkY',
    appId: '1:672595274421:web:1ff01889a3fa186275acfc',
    messagingSenderId: '672595274421',
    projectId: 'swiftdine-86be0',
    authDomain: 'swiftdine-86be0.firebaseapp.com',
    databaseURL: 'https://swiftdine-86be0-default-rtdb.firebaseio.com',
    storageBucket: 'swiftdine-86be0.firebasestorage.app',
    measurementId: 'G-194F19YDVT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgx8RsoHvNJTHN5ew7nBk-7-yqNtLkfgI',
    appId: '1:672595274421:android:a129397dd8443d5075acfc',
    messagingSenderId: '672595274421',
    projectId: 'swiftdine-86be0',
    databaseURL: 'https://swiftdine-86be0-default-rtdb.firebaseio.com',
    storageBucket: 'swiftdine-86be0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAG_c2zjkeGdXfdtBKxm6ua-2nidfQLtRs',
    appId: '1:672595274421:ios:9c90c080fbb248c775acfc',
    messagingSenderId: '672595274421',
    projectId: 'swiftdine-86be0',
    databaseURL: 'https://swiftdine-86be0-default-rtdb.firebaseio.com',
    storageBucket: 'swiftdine-86be0.firebasestorage.app',
    iosBundleId: 'com.example.mezaRestaurant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAG_c2zjkeGdXfdtBKxm6ua-2nidfQLtRs',
    appId: '1:672595274421:ios:9c90c080fbb248c775acfc',
    messagingSenderId: '672595274421',
    projectId: 'swiftdine-86be0',
    databaseURL: 'https://swiftdine-86be0-default-rtdb.firebaseio.com',
    storageBucket: 'swiftdine-86be0.firebasestorage.app',
    iosBundleId: 'com.example.mezaRestaurant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCT33HQ8W7qjNy7GEaLlMHH46p40_ohqkY',
    appId: '1:672595274421:web:d990659aa6a9afcb75acfc',
    messagingSenderId: '672595274421',
    projectId: 'swiftdine-86be0',
    authDomain: 'swiftdine-86be0.firebaseapp.com',
    databaseURL: 'https://swiftdine-86be0-default-rtdb.firebaseio.com',
    storageBucket: 'swiftdine-86be0.firebasestorage.app',
    measurementId: 'G-1HJMYRMDTT',
  );
}
